wandb_version: 1

obs_dim:
  desc: null
  value: 20402
action_dim:
  desc: null
  value: 2
latent_dim:
  desc: null
  value: 5
num_episodes:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.12
    cli_version: 0.18.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728423441
    t:
      1:
      - 1
      - 55
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      - 55
      4: 3.8.12
      5: 0.18.3
      8:
      - 5
      13: linux-x86_64
