_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
action_dim:
    value: 2
latent_dim:
    value: 5
num_episodes:
    value: 1000
obs_dim:
    value: 20402
